# Generated by Django 3.2.6 on 2021-08-14 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prjects',
            new_name='Projects',
        ),
    ]
